language: haskell

env:
  - GHCVER=8.0.2
  - GHCVER=8.2.2
  - GHCVER=8.4.1
  - GHCVER=head

matrix:
  allow_failures:
    - env: GHCVER=head

before_install:
  # If $GHCVER is the one travis has, don't bother reinstalling it.
  # We can also have faster builds by installing some libraries with
  # `apt`. If it isn't, install the GHC we want from hvr's PPA along
  # with cabal-1.18.
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install cabal-install-1.22 ghc-$GHCVER-prof ghc-$GHCVER-dyn happy
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/1.22/bin:$PATH
  # Uncomment whenever hackage is down.
  # - mkdir -p ~/.cabal && cp travis/config ~/.cabal/config && $CABAL update
  - cabal update

  # Update happy when building with GHC head
  - |
    if [ $GHCVER = "head" ] || [ $GHCVER = "7.8.4" ] || [ $GHCVER = "7.10.1" ]; then
      cabal install --constraint=transformers\ installed happy alex
      export PATH=$HOME/.cabal/bin:$PATH
    fi

install:
  - cabal install --dependencies-only --enable-tests
  - cabal configure --enable-tests $MODE

script:
  - cabal build
  - cabal test --show-details=always

  # run cabal package checks.
  - cabal check
